version: 2
jobs:
  Linux:
    docker:
      - image: brettrtoomey/vapor1-ci:0.0.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-spm-deps-{{ checksum "Package.pins" }}
      - run:
          name: Copy Pins Package
          command: cp Package.pins res
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - run:
          name: Restoring Pins Package
          command: mv res Package.pins
      - save_cache:
          key: v2-spm-deps-{{ checksum "Package.pins" }}
          paths:
            - .build
workflows:
  version: 2
  build-and-test:
    jobs:
      - Linux
experimental:
  notify:
    branches:
      only:
        - master
        - develop
